// Database Schema Definitions for Pehenava E-commerce Platform

export const COLLECTIONS = {
  USERS: "users",
  PRODUCTS: "products",
  ORDERS: "orders",
  ORDER_ITEMS: "order_items",
  CART: "cart",
  WISHLIST: "wishlist",
  REVIEWS: "reviews",
  CATEGORIES: "categories",
  BRANDS: "brands",
  COUPONS: "coupons",
  ADDRESSES: "addresses",
  PAYMENTS: "payments",
  NOTIFICATIONS: "notifications",
  MARKETS: "markets",
  SHOPS: "shops",
  EMAIL_OTPS: "email_otps",
  APPLICATIONS: "applications",
};

export const USER_SCHEMA = {
  _id: "ObjectId",
  userId: "String (unique)",
  email: "String (unique, required)",
  password: "String (hashed)",
  name: "String (required)",
  phone: "String",
  avatar: "String (URL)",
  dateOfBirth: "Date",
  gender: "String (male/female/other)",
  emailVerified: "Boolean (default: false)",
  phoneVerified: "Boolean (default: false)",
  isActive: "Boolean (default: true)",
  role: "String (customer/seller/admin)",
  preferences: {
    newsletter: "Boolean",
    notifications: "Boolean",
    theme: "String (light/dark)",
    language: "String",
  },
  addresses: ["ObjectId (ref: addresses)"],
  createdAt: "Date",
  updatedAt: "Date",
  lastLoginAt: "Date",
};

export const PRODUCT_SCHEMA = {
  _id: "ObjectId",
  productId: "String (unique)",
  name: "String (required)",
  slug: "String (unique, required)",
  description: "String (required)",
  shortDescription: "String",
  price: "Number (required)",
  originalPrice: "Number",
  discount: "Number (calculated)",
  category: "String (required)",
  subcategory: "String",
  brand: "String",
  sku: "String (unique)",
  images: ["String (URLs)"],
  thumbnail: "String (URL)",
  colors: ["String"],
  sizes: ["String"],
  materials: ["String"],
  careInstructions: "String",
  inStock: "Boolean (default: true)",
  stockQuantity: "Number (default: 0)",
  minOrderQuantity: "Number (default: 1)",
  maxOrderQuantity: "Number",
  weight: "Number (in grams)",
  dimensions: {
    length: "Number",
    width: "Number",
    height: "Number",
  },
  tags: ["String"],
  rating: "Number (0-5)",
  reviewCount: "Number (default: 0)",
  viewCount: "Number (default: 0)",
  isFeatured: "Boolean (default: false)",
  isNew: "Boolean (default: true)",
  isBestSeller: "Boolean (default: false)",
  isOnSale: "Boolean (default: false)",
  shopId: "String (required)",
  marketId: "String (required)",
  sellerId: "String (required)",
  status: "String (active/inactive/draft)",
  seoTitle: "String",
  seoDescription: "String",
  createdAt: "Date",
  updatedAt: "Date",
  publishedAt: "Date",
};

export const ORDER_SCHEMA = {
  _id: "ObjectId",
  orderId: "String (unique, required)",
  userId: "String (required)",
  status:
    "String (pending/confirmed/processing/shipped/delivered/cancelled/returned)",
  paymentStatus: "String (pending/paid/failed/refunded)",
  shippingStatus: "String (pending/processing/shipped/delivered)",
  subtotal: "Number (required)",
  tax: "Number (default: 0)",
  shipping: "Number (default: 0)",
  discount: "Number (default: 0)",
  total: "Number (required)",
  currency: "String (default: INR)",
  paymentMethod: "String (cod/card/upi/netbanking/wallet)",
  paymentId: "String",
  shippingAddress: {
    name: "String",
    phone: "String",
    address: "String",
    city: "String",
    state: "String",
    pincode: "String",
    country: "String (default: India)",
    landmark: "String",
  },
  billingAddress: {
    name: "String",
    phone: "String",
    address: "String",
    city: "String",
    state: "String",
    pincode: "String",
    country: "String (default: India)",
    landmark: "String",
  },
  trackingNumber: "String",
  estimatedDelivery: "Date",
  deliveredAt: "Date",
  notes: "String",
  couponCode: "String",
  createdAt: "Date",
  updatedAt: "Date",
};

export const ORDER_ITEM_SCHEMA = {
  _id: "ObjectId",
  orderId: "String (required)",
  productId: "String (required)",
  productName: "String (required)",
  productImage: "String",
  price: "Number (required)",
  quantity: "Number (required)",
  total: "Number (calculated)",
  size: "String",
  color: "String",
  sellerId: "String (required)",
  shopId: "String (required)",
  status:
    "String (pending/confirmed/processing/shipped/delivered/cancelled/returned)",
  createdAt: "Date",
};

export const CART_SCHEMA = {
  _id: "ObjectId",
  userId: "String (unique, required)",
  items: [
    {
      productId: "String (required)",
      quantity: "Number (required)",
      size: "String",
      color: "String",
      addedAt: "Date",
    },
  ],
  totalItems: "Number (calculated)",
  subtotal: "Number (calculated)",
  createdAt: "Date",
  updatedAt: "Date",
};

export const WISHLIST_SCHEMA = {
  _id: "ObjectId",
  userId: "String (required)",
  productId: "String (required)",
  addedAt: "Date",
  UNIQUE: ["userId", "productId"],
};

export const REVIEW_SCHEMA = {
  _id: "ObjectId",
  reviewId: "String (unique)",
  userId: "String (required)",
  productId: "String (required)",
  orderId: "String (required)",
  rating: "Number (1-5, required)",
  title: "String",
  comment: "String",
  images: ["String (URLs)"],
  isVerified: "Boolean (default: false)",
  isHelpful: "Number (default: 0)",
  isReported: "Boolean (default: false)",
  response: {
    sellerId: "String",
    comment: "String",
    respondedAt: "Date",
  },
  status: "String (pending/approved/rejected)",
  createdAt: "Date",
  updatedAt: "Date",
};

export const ADDRESS_SCHEMA = {
  _id: "ObjectId",
  userId: "String (required)",
  type: "String (home/office/other)",
  name: "String (required)",
  phone: "String (required)",
  address: "String (required)",
  city: "String (required)",
  state: "String (required)",
  pincode: "String (required)",
  country: "String (default: India)",
  landmark: "String",
  isDefault: "Boolean (default: false)",
  createdAt: "Date",
  updatedAt: "Date",
};

export const COUPON_SCHEMA = {
  _id: "ObjectId",
  code: "String (unique, required)",
  name: "String (required)",
  description: "String",
  type: "String (percentage/fixed)",
  value: "Number (required)",
  minOrderAmount: "Number (default: 0)",
  maxDiscount: "Number",
  usageLimit: "Number",
  usedCount: "Number (default: 0)",
  validFrom: "Date (required)",
  validUntil: "Date (required)",
  isActive: "Boolean (default: true)",
  applicableCategories: ["String"],
  applicableProducts: ["String"],
  createdAt: "Date",
  updatedAt: "Date",
};

export const NOTIFICATION_SCHEMA = {
  _id: "ObjectId",
  userId: "String (required)",
  type: "String (order/payment/shipping/promotion/system)",
  title: "String (required)",
  message: "String (required)",
  data: "Object",
  isRead: "Boolean (default: false)",
  isImportant: "Boolean (default: false)",
  createdAt: "Date",
  readAt: "Date",
};

export const CATEGORY_SCHEMA = {
  _id: "ObjectId",
  categoryId: "String (unique)",
  name: "String (required)",
  slug: "String (unique, required)",
  description: "String",
  image: "String (URL)",
  parentId: "String (for subcategories)",
  level: "Number (0 for main category)",
  isActive: "Boolean (default: true)",
  sortOrder: "Number (default: 0)",
  seoTitle: "String",
  seoDescription: "String",
  createdAt: "Date",
  updatedAt: "Date",
};

export const BRAND_SCHEMA = {
  _id: "ObjectId",
  brandId: "String (unique)",
  name: "String (required)",
  slug: "String (unique, required)",
  description: "String",
  logo: "String (URL)",
  website: "String (URL)",
  isActive: "Boolean (default: true)",
  createdAt: "Date",
  updatedAt: "Date",
};

// Index definitions for better performance
export const INDEXES = {
  users: [{ email: 1 }, { userId: 1 }, { phone: 1 }, { createdAt: -1 }],
  products: [
    { productId: 1 },
    { slug: 1 },
    { category: 1 },
    { brand: 1 },
    { price: 1 },
    { rating: -1 },
    { createdAt: -1 },
    { isFeatured: 1, createdAt: -1 },
    { isBestSeller: 1, rating: -1 },
    { name: "text", description: "text", tags: "text" },
  ],
  orders: [
    { orderId: 1 },
    { userId: 1 },
    { status: 1 },
    { createdAt: -1 },
    { userId: 1, status: 1 },
  ],
  order_items: [{ orderId: 1 }, { productId: 1 }, { sellerId: 1 }],
  cart: [{ userId: 1 }],
  wishlist: [{ userId: 1 }, { productId: 1 }, { userId: 1, productId: 1 }],
  reviews: [
    { productId: 1 },
    { userId: 1 },
    { rating: 1 },
    { createdAt: -1 },
    { productId: 1, rating: 1 },
  ],
  addresses: [{ userId: 1 }, { userId: 1, isDefault: 1 }],
  notifications: [{ userId: 1 }, { userId: 1, isRead: 1 }, { createdAt: -1 }],
};
